server:
  port: 8080

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    br.com.devfest.codecash: DEBUG

spring:
  application:
    name: codecash
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/codecash"
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
    redis:
      time-to-live: 10m
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    title: Code & Cash API
    description: Documentation for all code & cash api endpoints (REST and GraphQL)
    path: /swagger-ui.html






